kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-viewer
  namespace: default
subjects:
- kind: ServiceAccount
  name: client-server-job
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-viewer
  apiGroup: rbac.authorization.k8s.io
