---
name: Container Image

on:
  pull_request:
    branches:
    - master

jobs:
  # https://help.github.com/en/actions/language-and-framework-guides/publishing-docker-images
  container-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Push to Docker Hub
      # https://github.com/docker/build-push-action
      uses: docker/build-push-action@v1
      with:
        repository: karlkfi/kubexit
        # Docker Automated Builds handle publishing
        push: false
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          repository: karlkfi/kubexit
          push: false
      - name: Setup kube tools
        id: setup
        uses: yokawasa/action-setup-kube-tools@v0.1.0
        with:
          kubectl: '1.18.2'
          kustomize: '3.8.1'
      - name: Create kind cluster
        uses: engineerd/setup-kind@v0.4.0
        with:
          version: v0.8.1
          name: e2e-test
      - name: Print Context
        run: |
          kubectl=${{steps.setup.outputs.kubectl-path}}
          cp "${kubectl}" /usr/local/bin/kubectl
          kustomize=${{steps.setup.outputs.kustomize-path}}
          cp "${kustomize}" /usr/local/bin/kustomize

          kubectl version --client
          kustomize version

          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" "$(kubectl config current-context)"
          echo "environment-kubeconfig:" "${KUBECONFIG}"
      - name: Apply job
        env:
          TEST_PATH: ci/e2e-test/client-server
        run: |
          cd "${TEST_PATH}"
          kustomize edit set image karlkfi/kubexit=karlkfi/kubexit:latest
          kustomize build . | kubectl apply -f -
      - name: Await job
        run: |
          kubectl wait pod --selector=job-name=client-server-job --for=condition=Initialized --timeout=2m
          timeout=120
          SECONDS=0
          while (( SECONDS < timeout )); do
            job_status=$(kubectl get pods --selector=job-name=client-server-job -o jsonpath="{.items[*].status.containerStatuses[*].state.terminated.reason}")
            if [[ "${job_status}" == *"Completed" -o "${job_status}" == *"Error" ]]; then
              echo "Status: ${job_status}"
              break
            fi
            sleep 2
          done
          kubectl logs --selector=job-name=client-server-job --all-containers --tail=-1
          kubectl get pods --selector=job-name=client-server-job -o yaml
      - name: Delete kind cluster
        if: always()
        run: kind delete cluster --name e2e-test
